allowBuilds:
  esbuild: true
minimumReleaseAgeExclude:
  - experimental-visualizer@1.0.0
overrides:
  isometric-physics: 'link:../isometric-physics'
  react-isometric-engine: 'link:../react-isometric-engine'
